import esbuild from "esbuild";
import process from "process";
import alias from "esbuild-plugin-alias";
import path from "path";


// The banner require mock is to handle js-yaml's require of buffer & esprima
const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
let __pagegit_banner_require = require
var require = function(id) {
  if (id === 'buffer') return { Buffer: globalThis.Buffer };
  if (id === 'esprima') return {};
  return __pagegit_banner_require(id);
};
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	inject: [
		"./buffer-shim.mjs"
	],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	platform: "browser",

	plugins: [
        alias({
            // 3. 强制解析：当代码里 require('buffer') 时，
            // 实际上去加载 node_modules/buffer 文件夹
            'buffer': path.resolve('node_modules/buffer/index.js'),
            
            // 4. 强制解析：当代码里 require('path') 时，
            // 加载 path-browserify
            'path': path.resolve('node_modules/path-browserify/index.js'),
            
            // 5. 屏蔽错误：当代码里 require('esprima') 时，
            // 加载我们的空文件，防止报错
            'esprima': path.resolve('empty-mock.mjs'),
        }),
    ],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
